name: Release Gem

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push:
    name: Push to RubyGems
    runs-on: ubuntu-latest
    environment: rubygems
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - uses: rubygems/release-gem@v1
